# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qr_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QrLoginDialog(object):
    def setupUi(self, QrLoginDialog):
        QrLoginDialog.setObjectName("QrLoginDialog")
        QrLoginDialog.resize(400, 300)
        self.LoginTextLabel = QtWidgets.QLabel(QrLoginDialog)
        self.LoginTextLabel.setGeometry(QtCore.QRect(120, 10, 151, 16))
        self.LoginTextLabel.setObjectName("LoginTextLabel")
        self.QuitButton = QtWidgets.QPushButton(QrLoginDialog)
        self.QuitButton.setGeometry(QtCore.QRect(80, 260, 75, 23))
        self.QuitButton.setObjectName("QuitButton")
        self.RefreshQrButton = QtWidgets.QPushButton(QrLoginDialog)
        self.RefreshQrButton.setGeometry(QtCore.QRect(260, 260, 75, 23))
        self.RefreshQrButton.setObjectName("RefreshQrButton")
        self.QrCodeView = QtWidgets.QGraphicsView(QrLoginDialog)
        self.QrCodeView.setGeometry(QtCore.QRect(100, 40, 200, 200))
        self.QrCodeView.setObjectName("QrCodeView")

        self.retranslateUi(QrLoginDialog)
        QtCore.QMetaObject.connectSlotsByName(QrLoginDialog)

    def retranslateUi(self, QrLoginDialog):
        _translate = QtCore.QCoreApplication.translate
        QrLoginDialog.setWindowTitle(_translate("QrLoginDialog", "钉钉扫码登录"))
        self.LoginTextLabel.setText(_translate("QrLoginDialog", "请使用钉钉扫描二维码登录"))
        self.QuitButton.setText(_translate("QrLoginDialog", "退出"))
        self.RefreshQrButton.setText(_translate("QrLoginDialog", "刷新二维码"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QrLoginDialog = QtWidgets.QDialog()
    ui = Ui_QrLoginDialog()
    ui.setupUi(QrLoginDialog)
    QrLoginDialog.show()
    sys.exit(app.exec_())
