# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\userlogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserNameLogin(object):
    def setupUi(self, UserNameLogin):
        UserNameLogin.setObjectName("UserNameLogin")
        UserNameLogin.resize(389, 300)
        self.LoginLabel = QtWidgets.QLabel(UserNameLogin)
        self.LoginLabel.setGeometry(QtCore.QRect(160, 40, 54, 12))
        self.LoginLabel.setObjectName("LoginLabel")
        self.PasswdLabel = QtWidgets.QLabel(UserNameLogin)
        self.PasswdLabel.setGeometry(QtCore.QRect(110, 140, 24, 16))
        self.PasswdLabel.setObjectName("PasswdLabel")
        self.QuitBotton = QtWidgets.QPushButton(UserNameLogin)
        self.QuitBotton.setGeometry(QtCore.QRect(90, 220, 75, 23))
        self.QuitBotton.setObjectName("QuitBotton")
        self.LoginBotton = QtWidgets.QPushButton(UserNameLogin)
        self.LoginBotton.setGeometry(QtCore.QRect(230, 220, 75, 23))
        self.LoginBotton.setObjectName("LoginBotton")
        self.splitter_2 = QtWidgets.QSplitter(UserNameLogin)
        self.splitter_2.setGeometry(QtCore.QRect(100, 100, 169, 20))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.UserNameLabel = QtWidgets.QLabel(self.splitter_2)
        self.UserNameLabel.setObjectName("UserNameLabel")
        self.UserNameInput = QtWidgets.QLineEdit(self.splitter_2)
        self.UserNameInput.setObjectName("UserNameInput")
        self.PasswdInput = QtWidgets.QLineEdit(UserNameLogin)
        self.PasswdInput.setGeometry(QtCore.QRect(150, 140, 121, 20))
        self.PasswdInput.setObjectName("PasswdInput")

        self.retranslateUi(UserNameLogin)
        QtCore.QMetaObject.connectSlotsByName(UserNameLogin)

    def retranslateUi(self, UserNameLogin):
        _translate = QtCore.QCoreApplication.translate
        UserNameLogin.setWindowTitle(_translate("UserNameLogin", "用户登录"))
        self.LoginLabel.setText(_translate("UserNameLogin", "用户登录"))
        self.PasswdLabel.setText(_translate("UserNameLogin", "密码"))
        self.QuitBotton.setText(_translate("UserNameLogin", "退出"))
        self.LoginBotton.setText(_translate("UserNameLogin", "登录"))
        self.UserNameLabel.setText(_translate("UserNameLogin", "用户名"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UserNameLogin = QtWidgets.QDialog()
    ui = Ui_UserNameLogin()
    ui.setupUi(UserNameLogin)
    UserNameLogin.show()
    sys.exit(app.exec_())
